USE project2_db;
INSERT INTO resources (link, tile, decription, category)
VALUES
("https://developers.google.com/web/tools/chrome-devtools/?hl=en", "Chrome Developer Tools", " ", "General Tools"),
("https://medium.freecodecamp.org/", "Free Code Camp", " ", "Teaching Resource"),
("https://validator.w3.org/#validate_by_input", "HTML Validator", " ", "HTML"),
("https://www.bootstrapcdn.com/fontawesome/", "Font Awesome", " ", "CSS"),
("https://fonts.google.com/", "Google Fonts", " ", "CSS"),
("https://getbootstrap.com/", "Bootstrap", " ", "CSS"),
("https://sizzy.co/", "Sizzy", "Sizzy is a tool for developing responsive websites crazy-fast. It allows you to preview an url on multiple devices at once, filter the devices, zoom them in and out, and more. ", "Testing"),
("http://forcemipsum.com/", "Star War Lorem Generator", " ", "Random"),
("https://codepen.io/search/pens?q=bootstrap%20social%20icons&page=1&order=popularity&depth=everything&show_forks=false", "Code Pen", "Bootstrap examples. ", "CSS"),
("https://www.iconfinder.com/search/?q=web", "Icon Finder", "Free icons for sites ", "CSS"),
("https://www.w3schools.com/js/js_array_methods.asp", "Javascript Array Methods", " ", "JS"),
("https://bootstrapcreative.com/resources/bootstrap-4-css-classes-index/", "Boot Strap Classes", "List of all bootstrap classes ", "CSS"),
("https://uigradients.com/#Sunset", "UI Gradients", "Gradient color tool. ", "CSS"),
("http://code.jquery.com/", "jQuery CDN", " ", "JS"),
("https://api.jquery.com/", "jQuery API Documentation", " ", "JS"),
("https://css-tricks.com/snippets/javascript/javascript-keycodes/", "CSS Tricks for Key Codes", " ", "CSS"),
("https://www.w3schools.com/jquery/trysel.asp", "Try jQuery Selector", " ", "JS"),
("https://www.w3schools.com/jquery/jquery_events.asp", "jQuery Event Methods", " ", "JS"),
("https://www.youtube.com/watch?v=yKE7016Ioxc&feature=youtu.be", "jQuery YouTube Calculator", " ", "JS"),
("https://www.w3schools.com/jsref/jsref_parseint.asp", "Javascript parseInt() Fuction", " ", "JS"),
("https://standardjs.com/", "Javascript Standard Style", " ", "JS"),
("https://www.codewars.com/", "Code Wars", " ", "Teaching Resource"),
("https://www.hackerrank.com/?utm_medium=cpc&utm_source=google&utm_content=gobrd&utm_campaign=brand", "HackerRank", " ", "Teaching Resource"),
("https://developer.mozilla.org/en-US/", "Mozilla MDN", " ", "General Tools"),
("https://thenextweb.com/dd/2018/02/09/ex-googler-warns-coding-bootcamps-are-lacking-in-two-key-areas/?amp=1", "What Bootcamps Are Lacking", " ", "Articles"),
("https://market.mashape.com/explore", "Marketplace", "API resource ", "API"),
("https://firebase.google.com/docs/?authuser=0", "Firebase Documentation", " ", "Databases"),
("https://nodejs.org/en/", "Node.js", " ", "JS"),
("http://jsbin.com/licegizite/edit?js,console", "JS Bin", " ", "JS"),
("https://www.codeschool.com/", "Code School", " ", "Teaching Resource"),
("https://www.npmjs.com/package/nodemon", "Nodemon", " ", "NPM Packages"),
("https://medium.muz.li/15-must-have-chrome-extensions-for-web-designers-and-front-end-developer-b12c1bd9490c", "Must Have Chrome Extensions", " ", "General Tools"),
("http://www.anatomyofcode.com/", "Anatomy of Code", " ", "JS"),
("https://www.npmjs.com/package/body-parser", "Body-Parser", " ", "NPM Packages"),
("https://guides.github.com/features/mastering-markdown/", "Mastering Markdowns", " ", "General Tools"),
("https://github.com/teachcoding/expresstemplate-static", "Express Template", " ", "Templates"),
("https://medium.com/@jdan/i-peeked-into-my-node-modules-directory-and-you-wont-believe-what-happened-next-b89f63d21558", "Funny Node_modules Article", " ", "Articles"),
("http://osxdaily.com/2016/09/22/fix-wi-fi-problems-macos-sierra/", "Fix Wi-Fi Problems in macOS Sierra", " ", "Common Issues"),
("https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4", "Build a RESTful API Using Node and Express 4", " ", "NPM Packages"),
("https://scotch.io/tutorials/use-expressjs-to-get-url-and-post-parameters", "Use ExpressJS to Get URL and POST Parameters", " ", "NPM Packages"),
("https://www.codeschool.com/courses/building-blocks-of-express-js", "Building Blocks of Express.js", " ", "Teaching Resource"),
("https://webbootcampuci0118.slack.com/files/U8D22J4P5/FA36ZTF0Q/heroku_deployment_guide.md", "Heroku Deployement Guide", " ", "Teaching Resource"),
("https://www.upwork.com/?gclid=EAIaIQobChMIof_2_aK62gIVQm5-Ch0TDgbNEAAYASAAEgI7kPD_BwE", "Upwork Job Resource", " ", "Job Resource"),
("https://www.tutorialspoint.com/sql/sql_tutorial.pdf", "SQL Tutorial", " ", "Databases"),
("https://handlebarsjs.com/", "Handlebars", " ", "Templates"),
("https://github.com/teachcoding/expresstemplate-hbs", "Express Template Handlebars", " ", "Templates"),
("https://medium.com/codebuddies/getting-to-know-asynchronous-javascript-callbacks-promises-and-async-await-17e0673281ee", "Getting to know asynchronous JavaScript: Callbacks, Promises and Async/Await", " ", "JS"),
("https://www.codementor.io/hari577/object-relational-mapping-in-nodejs-with-sequelize-du1088h3l", "Object-Relational Mapping in Node.js with Sequelize", " ", "Articles"),
("https://www.npmjs.com/package/mysql2", "MySQL2 NPM Package", " ", "NPM Packages"),
("http://docs.sequelizejs.com/manual/tutorial/querying.html", "Sequalize Queries", " ", "Databases"),
("https://mochajs.org/", "Mocha Console Testing Tool", " ", "Testing"),
("http://www.chaijs.com/", "Chai Console Testing Tool", " ", "Testing"),
("https://httpstatuses.com/", "HTTP Status Codes", " ", "Testing"),
("https://clipboardjs.com/", "Clipboard.js NPM Package", " ", "NPM Packages"),
("https://medium.freecodecamp.org/what-exactly-is-node-js-ae36e97449f5", "What Exactly Is Node.js", " ", "Teaching Resource")